name: Socket Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  socket-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Socket CLI
        run: npm i -g socket

      - name: Run Socket scan
        env:
          SOCKET_SECURITY_API_TOKEN: ${{ secrets.SOCKET_TOKEN }}
        run: |
          socket scan create . --json > socket-report.json --fail-on=high
          
